src/index.html

Ten komentarz jest dodany w celu pokazania PR

test comment for pull request

---

bower.json
package.json
src/app/index.module.js
src/app/index.route.js
src/app/index.translator.js
src/assets/i18n/pl_PL/common.json
src/index.html

Nie jestem pewien, czy dobrze rozwiązałem zależności (jest różnica wersji, 2.9.2 i 2.10.0)

doinstalowany moduł ładowania tłumaczeń

---

.gitignore
src/app/backend/backend.module.js
src/app/backend/backend.service.js
src/app/backend/backend.spec.js

Moduł z serwisem i testami. Api cały czas się zmienia, nie wstawiałem nigdzie prawdziwych ścieżek.

szkielet backend service

---

src/app/index.module.js

Tak jak pisaliśmy, dodałem ngMateial, dzięki czemu powinno teraz działać.
Aby wszystko było poprawnie każdy musi zainstalować u siebie npm i 
bower install angular-material --save
i powinno działać :)

ngMaterial dodany do index.module

---

bower.json

Dodałem Angular Material, wywaliłem Material Design Lite i zależności - tak, żeby obcy robił pull, npm install, bower install, gulp serve i miał co trzeba.

Porządek z MDL i AM

---

src/assets/i18n/pl_PL/common.json

literówki w tłumaczeniu

---

src/app/backend/backend.module.js
src/app/backend/backend.service.js
src/app/backend/backend.spec.js

Wszystko jest na czerwono-zielono, bo miałem złe ustawienia wcięć, ale już to poprawiłem.
Dodałem url'e do mocka plus kilka dodatkowych funkcji.

wstawiono url'e do api i dodano kilka funkcji

---

src/app/backend/backend.service.js

Funkcja zwracała undefined, już powinno być dobrze.

Bugfix getDeckById;

---

src/app/backend/backend.service.js

Bugfix funkcji jsonToDecks.

---

src/app/index.route.js
src/app/landing/landing.controller.js
src/app/landing/landing.html
src/assets/i18n/pl_PL/common.json

W kontrolerze wystarczy jedynie podpiąć linki do Logowania i rejestracji

landing page

---

src/app/index.route.js
src/app/login/landing.controller.js
src/app/login/login.html
src/app/registration/registration.html

Do widoku talii (zaszytej na sztywno - Rafał?)

baza do demo

---

src/app/navbar/navbar.html
src/assets/icons/home.svg

Ikona home jest odnośnikiem do /decks

dodana ikona 'home' w navbarze

---

.gitignore
gulp/server.js
package.json
src/app/backend/backend.service.js
src/app/backend/backend.spec.js
src/app/decks/deck.html

Do poprawnego działania potrzebna jest mini baza danych w postaci [pliku json](http://pastebin.com/Dcurp0eg) do umieszczenia w głównym katalogu. Umieściłem go w .gitignore, bo lokalne zmiany u różnych osób będą powodować konflikty.
Potrzeba jeszcze pobrać gulp-json-srv poleceniem npm install.

Ulepszony mock, poprawiony.

---

src/app/deck/deck.controller.js
src/app/deck/deck.html
src/app/deck/deck.scss

fix do dodawania decków to jednak moja wina była

fix add deck

---

src/app/backend/backend.module.js
src/app/backend/backend.service.js
src/app/deck/deck.controller.js
src/app/deck/deck.directive.js
src/app/deck/deck.module.js
src/app/deck/deck.route.js
src/app/registration/compare.directive.js
src/app/registration/listenIfOnline.run.js
src/app/registration/registration.controller.js
src/app/registration/registration.module.js
src/app/registration/registration.route.js
src/app/studyBoxFe.layout.module.js
src/app/studyBoxFe.module.js
src/app/studyBoxFe.services.module.js

Zmiana nazwy modułu zgodnie z sugestią Jakuba, przystosowanie struktury do modularyzacji całości. Jak nie będzie sprzeciwów do wieczora, zrobię merge, bo to Wam w niczym bruździć nie powinno.

porządki w strukturze i wstęp do modularyzacji

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html
src/app/addCard/addCard.scss
src/app/deck/deck.page.html
src/assets/i18n/pl_PL/common.json

Jeszcze tylko odstępy między Marcina kontrolką, ale to się wystyluje jak zostanie zmieniona.

Dodano dużą część responsywności.

---

src/app/index.config.js

Wywalone błędne palety z konfiguracji.

drobna poprawka MD

---

gulp/server.js
src/app/backend/backend.service.js

Pozostała kwestia podłączenia innych modułów do serwisu, w szczególności `addCard`.

Podłączenie backend.service do prawdziwego backendu.

---

src/app/index.config.js
src/app/login/login.controller.js
src/app/login/login.html
src/app/login/splash.scss
src/app/registration/listenIfOnline.run.js
src/app/registration/registration.controller.js
src/app/registration/registration.html
src/assets/i18n/pl_PL/common.json
src/index.html

- splash-screen wraz z logo aplikacji
- poprawa formularza logowania(ujednolicenie styli po Maćku)
TODO:

STUDYBOX-34 / 189

---

src/app/deck/deck.controller.js
src/app/deck/deck.service.js

fix dla state'ów przy tworzeniu decka

#fix states for deck create

---

src/app/deck/deck.controller.js
src/app/deck/deck.html
src/app/deck/deck.service.js

Studybox 31 fix card obj service

---

src/app/networkStatus/listenIfOnline.run.js
src/app/registration/registration.html

Poprawione błędy libki wyświetlające błędy inputów
https://github.com/angular/material/issues/6767

STUDYBOX-35

---

src/app/login/login.controller.js
src/app/login/login.html
src/app/networkStatus/listenIfOnline.run.js
src/app/registration/registration.controller.js
src/app/registration/registration.html

Dodany dodatkowy dialog z informacją o braku połączenia z siecią podczas próby kliknięcia "Zarejestruj" oraz "Zaloguj"

poprawa inputow + dialogow

---

src/app/login/login.controller.js
src/app/networkStatus/listenIfOnline.run.js
src/app/registration/registration.controller.js
src/assets/i18n/pl_PL/common.json

- Zmiana "Podpowiedź" na "Dodaj podpowiedź"
- Przy okazji dodano tłumaczenia w alertach globalnych, rejestracji i logowania

STUDYBOX-266 - bugfix

---

src/app/deck/deck.controller.js
src/app/deck/deck.scss

bugfix na odznaczanie fiszki 
bugfix na czyszczenie servisu z deckiem po ponownym wejściu w widok talii

Studybox 251 bugfix

---

src/app/deck/deck.controller.js
src/app/deck/deck.scss
src/assets/i18n/pl_PL/common.json

bigfix STUDYBOX-263
bigfix STUDYBOX-264

Studybox 263/264 bugfix

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html

- Dodany min limit pytania i odpowiedzi
- Dodane sprawdzenie walidacji ilości znaków i blokada akcji

STUDYBOX-267 - bugfix

---

src/app/deck/deck.controller.js
src/assets/i18n/pl_PL/common.json

- Dodany dialog alert sprawdzający połączenie z internetem w momencie chęci usunięcia fiszki

STUDYBOX-271 - bugfix

---

src/app/decks/decks.html
src/app/decks/decks.route.js
src/app/index.route.js
src/app/login/login.controller.js
src/app/login/login.html
src/app/login/login.module.js
src/app/login/login.service.js
src/app/navbar/navbar.html
src/app/registration/registration.route.js
src/app/studyBoxFe.module.js
src/assets/i18n/pl_PL/common.json

Otwieram requesta, żebyście wiedzieli, czego się spodziewać. Na razie nic specjalnego nie robi, ale nie psuje też niczego - i działa, więc jak ktoś bardzo potrzebuje, to może zrobić merge ;)

STUDYBOX-238 - [FE] Dodanie komunikacji z BE dla logowania

---

src/app/deck/deck.controller.js
src/app/navbar/navbar.html

- Zmieniono zachowanie dialogu, tj. gdy utracimy połączenie i naciśniemy przycisk usuwający fiszkę wywoła się informacja o tym, że usuwanie nie jest możliwe przez brak połączenia.
- Dodano małe zmiany w wyświetlaniu danych w hamburger menu

STUDYBOX-271 - bugfix aktualizacja

---

src/app/deck/deck.controller.js
src/assets/i18n/pl_PL/common.json

Studybox 263/264 fixes

---

src/assets/i18n/pl_PL/common.json

usunięcie spacji i przecinka ...

Studybox 264 fix

---

src/assets/i18n/pl_PL/common.json

fix STUDYBOX-283

---

src/app/deck/deck.controller.js

bug fix
zmiana kolejności wywołania funkcji

fix STUDYBOX-286

---

src/app/deck/deck.controller.js

jako, że testerzy i analiza szaleje, znów zmieniam string na taki jak był wcześniej ...

bugfix_263/264

---

src/app/addCard/addCard.controller.js
src/app/backend/backend.service.js
src/app/deck/deck.controller.js
src/app/deck/deck.html
src/app/deck/deck.service.js

dodano setowanie przy tworzeniu i edycję dostępu do talii public/private
narazie nie działa po stronie BE(nie zwraca parametru isPublic dal talii) wiec na razie zawsze fiszki danego uzytkownika są prywatne

set deck access

---

src/app/deck/deck.controller.js
src/app/deck/deck.html

Mozilla fix

---

src/app/deck/deck.controller.js
src/app/login/login.config.js
src/app/login/login.controller.js
src/app/login/login.html
src/app/login/login.service.js
src/app/login/loginHelper.service.js
src/app/login/loginInterceptor.factory.js
src/assets/i18n/pl_PL/common.json

macie, na szybko, kto potrzebuje, niech zerknie i zrobi merge

tymczasowo dodany userName

---

src/app/navbar/navbar.controller.js
src/app/navbar/navbar.html
src/app/navbar/navbar.scss

Poprawiony wygląd md-autocomplete,
pozbycie się błędów,
poprawa działania

STUDYBOX-123

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html
src/app/addCard/addCard.scss

- Możliwość wpisania więcej niż 10 znaków(na potrzeby demo), ale gdy tylko wkleimy coś dłuższego niż 10 znaków input automatycznie jest przycinany do 10. W późniejszej fazie licznik zapalać się będzie na czerwono po przekroczeniu bariery(domyślnie 1000 znaków)

STUDYBOX-260 - bugfix

---

src/app/deck/deck.controller.js
src/app/registration/registration.html

- Usunięto konkretny dialog przy usuwaniu zgodnie z ustaleniami project ownera
Tym samym jedyne info o braku neta, to info globalne.

STUDYBOX-271 - bugfix aktualizacja 2

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html
src/app/addCard/addCard.scss

- Zgodnie z założeniami project ownera dodane ucinanie do 1k znaków jedynie przy wklejaniu. Wpisując z palca po przekroczeniu 1k znaków licznik zapala się na czerwono i wysłanie nie będzie możliwe("Poza licznikiem nie będzie innych komunikatów").

STUDYBOX-260 - bugfix aktualizacja

---

src/app/deck/deck-edit.controller.js
src/app/deck/deck-edit.page.html
src/app/deck/deck-preview.controller.js
src/app/deck/deck.scss
src/app/deck/my-deck-preview.page.html

fix na wykrywanie zmian zapisu dla publicznej/prywatnej talii

fix STUDYBOX-329

---

src/app/deck/deck-edit.page.html

1 linijka , zapis zmiany talii przy enterze

save on enter fix

---

src/assets/i18n/pl_PL/common.json

- Zmiana opcji z "Nie" na "Anuluj"

STUDYBOX-358 - bugfix

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html
src/app/addCard/addCard.scss
src/assets/i18n/pl_PL/common.json

- Dodano możliwość dodawania do 5 podpowiedzi w ekranie dodawania fiszek oraz ich pojedynczego usuwania
- Poprawiono zachowanie translacji przycisku dodającego podpowiedzi
- Walidacja ilości wprowadzonych znaków do inputów z podpowiedziami
TODO
Wyczyszczenie paru linijek gdy zasady walidacji ilości tekstu będą na pewno poprawne u analityków

STUDYBOX-265/267/275 - bugfix

---

src/app/backend/backend.service.js
src/app/backend/deck.factory.js
src/app/backend/flashcard.factory.js
src/app/backend/tip.factory.js

Jak w temacie. Należy jedynie powypełniać puste funkcje.

Szkielet nowego backend.service.

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html

- Zgodnie z poprawkami epicka, spacje mają być liczone w inputach

STUDYBOX-397/381 - bugfix

---

src/app/deck/my-deck-preview.page.html

Dodaję jedną poprawkę, podgląd prywatnych talii. Zobaczcie, czy o to chodziło.

RWD - poprawka podglądu prywatnych talii

---

gulp/styles.js
src/app/login/login.html
src/app/navbar/navbar.html
src/app/registration/registration.html
src/assets/styles/base.scss
src/index.html

Uwaga, ważna zmiana!
Jest zrobiony base.scss, w katalogu /assets/styles/ - to jest plik na globalne style dla całej aplikacji, jeśli się okażą niezbędne. Na razie potrzebne było ustawienie jednego height:100% ;)
Ten katalog to też miejsce na stylowanie elementów, które tego wymagają, a są używane w różnych miejscach. Jeśli ktoś chce np. zrobić ładnego buttona, który wyląduje w kilku widokach, to niech jego style umieści w pliku button.scss w tym katalogu. Umieszczone tam pliki *.scss będą inkludowane automatycznie przy budowaniu apki (zrobiłem poprawkę w gulpie).
Oprócz tego w tym pullu są wycentrowane panele logowania i rejestracji oraz wycięte zbędne (IMHO) divy.

RWD ciąg dalszy plus base.scss - początek porządkowania

---

src/app/studyBoxFe.module.js
src/app/test/answer.html
src/app/test/hint.html
src/app/test/question.html
src/app/test/test.controller.js
src/app/test/test.html
src/app/tips/tips.service.js
src/assets/i18n/pl_PL/common.json

wykluczenie ukrytych fiszek z testu

---

src/app/test/test.controller.js
src/assets/i18n/pl_PL/common.json

fix:
jeśli było 100% poprawnych odpowiedzi widoczna jest etykieta "powtórz test", jeśli mniej "popraw wynik"

Studybox 341

---

src/app/backend/backend.service.js
src/app/deck/deck-edit.controller.js
src/app/deck/deck-edit.page.html

fix na zmiane widoczności talii (BE nie działa do onca można zmienić  publicznej na prywatną w drugą strone nie działa)
fix na zapis nazwy talii

Studybox 403

---

src/app/deck/my-deck-preview.controller.js
src/app/studyBoxFe.module.js
src/app/test/answer.html
src/app/test/hint.html
src/app/test/question.html
src/app/test/test.controller.js
src/app/test/test.html
src/app/tips/tips.service.js
src/assets/i18n/pl_PL/common.json

dodanie podpowiedzi w trybie testu

Tryb testu tips

---

src/app/test/dialog.html
src/app/test/piechart.directive.js
src/app/test/test.controller.js

STUDYBOX-430 Wykres kołowy dla wyników testu.

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html
src/app/addCard/addCard.scss
src/app/deck/deck-edit.controller.js
src/app/deck/deck-edit.page.html
src/app/deck/deck-preview.page.html
src/app/deck/deck.scss
src/app/deck/my-deck-preview.controller.js
src/app/deck/my-deck-preview.page.html
src/app/navbar/hamburgerMenu.html
src/assets/i18n/pl_PL/common.json

- Poprawienie ukrywania i odkrywania fiszki,
- Poprawienie ikon tak, by po naciśnięciu na nie nie pokazywała się niebieska ramka symbolizująca focus,
- Niezalogowany użytkownik nie zobaczy już przycisku "Moje talie".

STUDYBOX-333 i drobne poprawki

---

src/app/backend/flashcard.factory.js

STUDYBOX-384 refactoring backend.service [FLASHCARDS]

---

src/app/addCard/addCard.html
src/app/deck/deck-edit.controller.js
src/assets/i18n/pl_PL/common.json

Zablokowanie testu gdy wszystkie fiszki ukryte

---

src/app/backend/backend.service.js
src/app/deck/deck.route.js
src/app/login/login.controller.js
src/app/login/login.html
src/assets/i18n/pl_PL/common.json

+ up
+ dodanie pola creatorEmail

Obsługa błędów pobierania talii

---

src/app/backend/backend.service.js
src/app/navbar/navbar.controller.js
src/app/navbar/navbar.html
src/app/navbar/topNavbarElements.html
src/assets/i18n/pl_PL/common.json

Poprawki z długiej listy zgłoszone przez testera.
Nie zrobiłem tylko tego: https://tracker.blstreamgroup.com/jira/browse/STUDYBOX-453 (nie mam pomysłu jak to w miarę prosto obsłużyć)
i tego: https://tracker.blstreamgroup.com/jira/browse/STUDYBOX-451 (wyniki wyszukiwania chyba miały być tylko w dropdown'ie, a nie na planszy?)

STUDYBOX-241 bugfix

---

src/app/deck/deck-edit.controller.js
src/app/deck/deck-edit.page.html

- Dodano jedynie wizualnie tagi ponieważ BE w najbliższych czasach nie ma w planach ich pełnej obsługi
- Zmodernizowano lekko wygląd lewej sekcji wyglądu edycji

STUDYBOX-385 - tagi

---

src/app/test/piechart.directive.js
src/assets/i18n/pl_PL/common.json

Zmieniłem kolory wykresu kołowego na bardziej pasujące (dark blue i raspberry).

Kolory piechart

---

src/app/decks/decks.controller.js
src/app/decks/decks.html
src/app/decks/decks.service.js
src/app/navbar/hamburgerMenu.html
src/app/navbar/navbar.controller.js
src/app/navbar/navbar.html
src/app/navbar/navbar.scss
src/assets/i18n/pl_PL/common.json

Wyszukiwanie zrobione tak, aby było zgodne z dokumentacją; czyli po zatwierdzeniu wyszukiwania enterem, wyniki wyświetlają się na planszy z taliami zamiast w dropdown'ie. Blokuje wprowadzanie ponad 100 znaków w wyszukiwarce.
Dodatkowo, usunięto ,,publiczne talie innych osób''.

Refactoring wyszukiwania talii.

---

src/app/backend/backend.service.js
src/app/backend/deck.factory.js

Brakujące pola: `creatorEmail`, `creationDate`.
Dodanie metody `BackendService.drawRandomDeck()`.
Dodanie funkcjonalności liczenia fiszek do `BackendService.getDecks()`.
Wyrzuciłem instrukcję obsługi, bo niektórzy zmieniają funkcje serwisu, zostawiając instrukcję nieaktualną.

Uzupełnienie brakujących pól talii i brakujących metod backend.service.

---

src/app/addCard/addCard.controller.js
src/app/addCard/addCard.html
src/app/backend/backend.service.js
src/app/deck/deck-preview.controller.js
src/app/deck/deck-preview.page.html
src/app/deck/my-deck-preview.controller.js
src/app/deck/my-deck-preview.page.html
src/app/deck/my-hintsList.html
src/app/tips/tips.service.js
src/assets/i18n/pl_PL/common.json
src/assets/icons/card.svg
src/assets/icons/clear.svg

- dodano CRUD dla podpowiedzi
- zmiana dwóch ikon(edycja, usuwanie)
- zmiana serwisu pobierania fiszek na pobieranie fiszek wraz z ilością podpowiedzi w nich
- zmiana nazwy pola serwisu podpowiedzi po aktualizacji API (content->essence)
TODO:

STUDYBOX-331 (podpowiedzi) + male zmiany ikonek

---

src/app/navbar/navbar.html
src/app/test/answer.html
src/app/test/hint.html
src/app/test/test.controller.js
src/assets/icons/not.svg

Fix tips in test

---

src/app/addCard/addCard.html
src/app/addCard/addCard.scss

- fix po którym można usuwać podpowiedzi
- dodany górną granice liczby znaków `/1000`

STUDYBOX-331 fix + licznik óorny znaków

---

src/app/decks/decks.controller.js
src/app/decks/decks.html
src/app/decks/decks.scss
src/app/navbar/navbar.controller.js
src/app/navbar/topNavbarElements.html
src/assets/i18n/pl_PL/common.json

* widok niezalogowanego użytkownika zgodnie z wymaganiami na jirze
* po otwarciu search'a focusuje się na nim

Widok niezalogowanego użytkownika

---

src/app/backend/backend.service.js
src/app/decks/decks.controller.js
src/app/decks/decks.html
src/app/decks/decks.route.js
src/app/decks/decks.service.js
src/app/index.route.js
src/app/login/login.config.js
src/app/navbar/navbar.controller.js
src/app/navbar/navbar.html
src/app/navbar/navbar.service.js

Utworzenie stanu `/decks-search`.
Próba przejścia do panelu logowania, będąc już zalogowanym, przekierowuje do `/decks`.
Tymczasowe wyłączenie ,,fixa'' w zamierzeniu poprawiającego problem inputa z hasłem - do poprawy dla Patryka. Bardzo obciąża przeglądarkę masą błędów.

bugfix STUDYBOX-539, STUDYBOX-528

---

src/app/login/login.html
src/app/navbar/hamburgerMenu.html
src/app/navbar/navbar.html
src/app/navbar/navbar.scss
src/app/navbar/newDeckFab.html
src/app/navbar/topNavbarElements.html
src/app/registration/registration.html
src/assets/styles/base.scss
src/index.html

Robię merge, ale wszelkie uwagi mile widziane :)

refaktoring RWD - zrobiony navbar dla różnych widoków

---

src/app/login/login.html
src/app/registration/registration.html

Wyłączyłem autocomplete w polach haseł w formularzach logowania i rejestracji

poprawka eliminująca śmieci w polu hasła

---

src/app/deck/deck.scss
src/app/deck/my-deck-preview.page.html

- usunięto błąd nie pojawiania się nazwy talii 
- przełamywanie linii w fiszkach by uniknąć zbyt wysokich kart

bug fix - nazwa tali/rozmiary fiszek

---

src/app/cards/card.directive.js
src/app/deck/cardEdit.html
src/app/deck/deck-preview.page.html
src/app/deck/deck.scss
src/app/deck/my-deck-preview.controller.js
src/app/deck/my-deck-preview.page.html

Popatrzcie i oceńcie, czy takie wyświetlanie ma sens.

wyświetlanie obrazków na fiszkach, początek

---

src/app/test/answer.html

Teraz działa kliknięcie na button, a nie tylko na ikonę.

poprawka buttonów w teście

---

src/app/deck/changeDeckName.html
src/assets/styles/base.scss

- poprawa inputa do wyszukiwania
- poprawa buttona zapisującego nazwę talii

Małe poprawki

---

src/app/deck/deck-preview.page.html
src/app/deck/my-deck-preview.page.html
src/app/test/answer.html
src/app/test/question.html

Nie ruszałem edycji fiszki, bo tu Patryk grzebie. Obejrzeć efekty można w talii ze stolicami.

wyświetlanie obrazków, podgląd (prywatny i publiczny) i test

---

src/app/deck/deck-preview.page.html
src/app/test/dialog.html
src/app/test/test.controller.js
src/assets/i18n/pl_PL/common.json

W panelu przeglądu cudzych talii, oba obrazki były takie same oraz najeżdżały na siebie.

Procenty w wyniku testu + fix obrazków

---

src/app/deck/deck.scss
src/app/deck/my-deck-preview.page.html

- ujednolicona wysokość karty dodającą nową fiszkę
- zmiana koloru ikonki podpowiedzi

Poprawki wyglądu karty
